
import type { Metadata } from "next";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v14-appRouter";
import {Roboto} from "next/font/google";
import {ThemeProvider} from "@mui/material/styles";
import localFont from "next/font/local";

import theme from '../theme';
import "./globals.css";
import { CurrentSkinContextProvider } from "../contexts/CurrentSkinContext";
import { LanguageContextProvider } from "@/contexts/LanguageContext";
import { SettingsContextProvider } from "@/contexts/SettingsContext";
import { SkinsContextProvider } from "@/contexts/SkinsContext";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.variable}`}
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <LanguageContextProvider>
              <SettingsContextProvider>
                <SkinsContextProvider>
                    <CurrentSkinContextProvider>
                          {children}
                    </CurrentSkinContextProvider>
                </SkinsContextProvider>
              </SettingsContextProvider>
            </LanguageContextProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
